---
services:

###########################################################################
###########################################################################
##
##  Docker Compose File: overseerr (LinuxServer.io)
##  Function: Overseerr allows requests for TV and mMvies
##
##  Documentation: https://docs.linuxserver.io/images/docker-overseerr
##  Image Link: https://github.com/linuxserver/docker-overseerr
##
###########################################################################
###########################################################################
  overseerr:
    image: lscr.io/linuxserver/overseerr:v1.33.2-ls89
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Americas/Denver
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /Users/johnvenable/Dockers/overseer/config:/app/config
    restart: unless-stopped

###########################################################################
###########################################################################
##
##  Docker Compose File: Sonarr (LinuxServer.io)
##  Function: Series Library Manager (TV Shows)
##
##  Documentation: https://docs.linuxserver.io/images/docker-sonarr
##  Image Link: https://github.com/linuxserver/docker-sonarr
##
###########################################################################
###########################################################################
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.0.748-ls220
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /Users/johnvenable/Dockers/sonarr/config:/config
      - /Volumes/Plex/TV:/tv #optional
      - /Users/johnvenable/Downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped


###########################################################################
###########################################################################
##
##  Docker Compose File: Radarr (LinuxServer.io)
##  Function: Movie Library Manager
##
##  Documentation: https://docs.linuxserver.io/images/docker-radarr
##  Image Link: https://github.com/linuxserver/docker-radarr
##
###########################################################################
###########################################################################
  radarr:
    image: lscr.io/linuxserver/radarr:5.2.6.8376-ls198
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /Users/johnvenable/Dockers/radarr/config:/config
      - /Volumes/Plex/Movies:/movies #optional
      - /Users/johnvenable/Downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped


###########################################################################
###########################################################################
##
##  Docker Compose File: Prowlarr (LinuxServer.io)
##  Function: Indexer and Search Manager
##
##  Documentation: https://docs.linuxserver.io/images/docker-prowlarr
##  Image Link: https://github.com/linuxserver/docker-prowlarr
##
###########################################################################
###########################################################################
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:1.11.4.4173-ls45
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Americas/Denver
    volumes:
      - /Users/johnvenable/Dockers/prowlarr/config:/config


###########################################################################
###########################################################################
##
##  Docker Compose File: Tautulli (LinuxServer.io)
##  Function: Monitoring, analytics and notifications for Plex Media Server.
##
##  Documentation: https://docs.linuxserver.io/images/docker-tautulli
##  Image Link: https://github.com/linuxserver/docker-tautulli
##
###########################################################################
###########################################################################
  tautulli:
    image: lscr.io/linuxserver/tautulli:v2.13.4-ls113
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Americas/Denver
    volumes:
      - /Users/johnvenable/Dockers/tautulli/config:/config
    ports:
      - 8181:8181
    restart: unless-stopped


###########################################################################
###########################################################################
##
##  Docker Compose File: qBittorrent (LinuxServer.io)
##  Function: Torrent Download Client
##
##  Documentation: https://docs.linuxserver.io/images/docker-qbittorrent
##  Image Link: https://github.com/linuxserver/docker-qbittorrent
##
###########################################################################
###########################################################################
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.2-r0-ls303
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Americas/Denver
      - WEBUI_PORT=8080
    volumes:
      - /Users/johnvenable/Dockers/qbittorrent/config:/config
      - /Users/johnvenable/Downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped


###########################################################################
###########################################################################
##
##  Docker Compose File: sabnzbd (LinuxServer.io)
##  Function: Usenet Download Client
##
##  Documentation: https://docs.linuxserver.io/images/docker-sabnzbd/
##  Image Link: https://github.com/linuxserver/docker-sabnzbd/
##
###########################################################################
###########################################################################
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:4.2.0-ls144
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Americas/Denver
    volumes:
      - /Users/johnvenable/Dockers/sabnzbd/config:/config
      - /Users/johnvenable/Downloads:/downloads
      - /Users/johnvenable/Downloads:/incomplete-downloads #optional
    ports:
      - 8081:8080
    restart: unless-stopped